apiVersion: v1
kind: Service
metadata:
  name: k6-webhook
  namespace: flagger-system
  labels:
    app: k6-webhook
spec:
  type: ClusterIP
  selector:
    app: k6-webhook
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
