apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- ../base
  - ../base/repository/metrics-server-helm.yaml
  - ../base/repository/istio-helm.yaml
  - ../base/repository/prometheus-helm.yaml
  - ../base/repository/kiali-helm.yaml
  - ../base/repository/aspire-helm.yaml
  - ../base/repository/grafana-helm.yaml
  - ../base/repository/flagger-helm.yaml
  - ../base/repository/vpa-helm.yaml
  - ../base/namespaces
  - ../base/crds
  - ../base/metrics-server
  - ../base/vpa
  #- ../base/istio-cni
  - ../base/istio-base
  - ../base/istiod
  - ../base/prometheus
  - ../base/prometheus-adapter
  - ../base/kube-state-metrics
  - ../base/flagger
  - ../base/grafana
  - ../base/kiali
  - ../base/aspire
  - ../base/locust
# patches:
#   - path: ./patches/istio-ingress-patch.yaml
