apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: locust
  labels:
    app: locust
    component: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: locust
      component: worker
  template:
    metadata:
      labels:
        app: locust
        component: worker
    spec:
      containers:
        - name: locust
          image: locustio/locust:2.20.1
          args:
            - --worker
            - --master-host=locust-master
            - --locustfile=/scripts/locustfile.py
          env:
            - name: MOCKERY_HOST
              value: "http://mockery.mockery.svc.cluster.local"
            - name: PODINFO_HOST
              value: "http://podinfo.podinfo.svc.cluster.local:9898"
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: scripts
          configMap:
            name: locust-scripts
