apiVersion: v1
kind: ServiceAccount
metadata:
  name: flagger-sa
  namespace: flagger-system
  labels:
    app.kubernetes.io/name: flagger
    app.kubernetes.io/instance: flagger
  annotations:
    # Azure Workload Identity annotations
    azure.workload.identity/client-id: "7887030e-7988-4805-88d3-e10e88e6ffe2"
    azure.workload.identity/tenant-id: "79a9ae56-fcc2-4717-a184-a409adf7d669"
