apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: mockery
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: mockery
  policy:
    semver:
      range: ^0.1.x
