apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repos
  - namespaces
  - crds
  - metrics-server
  - istio-base
  - istiod
  - prometheus
  - kube-state-metrics
  - flagger
  - grafana
  - aspire
