apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repos
  - namespaces
  - crds
  - metrics-server
  #- vpa
  - istio-cni
  - istio-base
  - istiod
  - prometheus
  - prometheus-adapter
  - kube-state-metrics
  - flagger
  - grafana
  #- kiali
  - aspire
  #- locust
