apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: weather-canary
spec:
  provider: istio
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weather
  progressDeadlineSeconds: 60
  service:
    port: 80
    targetPort: 8080
    portName: http
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
      - name: success-rate
        templateRef:
          name: request-success-rate
          namespace: flagger-system
        thresholdRange:
          min: 99
        interval: 1m
      - name: latency-p99
        templateRef:
          name: request-duration
          namespace: flagger-system
        thresholdRange:
          max: 500
        interval: 1m
    webhooks:
      - name: load-test
        url: http://flagger-loadtester.flagger-system/
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://weather-canary.weather/"
