apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - metrics-server-helm.yaml
  - istio-helm.yaml
  - prometheus-helm.yaml
  - kiali-helm.yaml
  - aspire-helm.yaml
  - grafana-helm.yaml
  - flagger-helm.yaml
