{
 "title": "Istio Mesh Dashboard",
 "tags": [ "istio" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"dashboard-header text-center\">\n<span>Istio Mesh Overview</span>\n</div>"
  },
  {
   "title": "Global Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=\"source\"}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Global Success Rate (non-5xx)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", response_code!~\"5.*\"}[1m])) / sum(irate(istio_requests_total{reporter=\"source\"}[1m]))"
    }
   ]
  },
  {
   "title": "Services in Mesh",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (app) (istio_requests_total{reporter=\"source\"}))"
    }
   ]
  },
  {
   "title": "P99 Latency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Request Rate by Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\"}[1m])) by (destination_workload, destination_workload_namespace)",
     "legendFormat": "{{destination_workload}}.{{destination_workload_namespace}}"
    }
   ]
  },
  {
   "title": "P99 Latency by Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace))",
     "legendFormat": "P99 {{destination_workload}}.{{destination_workload_namespace}}"
    }
   ]
  }
 ]
}