apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitor
resources:
  - httproute.yaml
  - helmrelease.yaml
  - istio-canary-configmap.yaml
  - istio-canary-overview-configmap.yaml
  - istio-workload-dashboard-configmap.yaml
  - istio-gateway-dashboard-configmap.yaml
  - kubernetes-hpa-dashboard-configmap.yaml
  - kubernetes-pod-health-dashboard-configmap.yaml
  - kubernetes-app-metrics-dashboard-configmap.yaml
  - prometheus-alertmanager-dashboard-configmap.yaml
  - istio-throttling-dashboard-configmap.yaml
