apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitor
resources:
  - httproute.yaml
  - helmrelease.yaml
  - istio-canary-configmap.yaml
  - istio-canary-overview-configmap.yaml
  - istio-throttling-configmap.yaml
  - istio-workload-configmap.yaml
  - istio-gateway-api-configmap.yaml
  - k8-hpa-configmap.yaml
  - k8-pod-health-configmap.yaml
  - k8-app-metrics-configmap.yaml
  - prometheus-alertmanager-dashboard-configmap.yaml
