{
 "title": "Prometheus Alertmanager",
 "description": "Dashboard showing Prometheus Alertmanager metrics for observing status of the cluster and possible debbuging.",
 "tags": [ "alertmanager" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(alertmanager_build_info)"
    }
   },
   { "name": "interval", "query": "2m" }
  ]
 },
 "panels": [
  { "title": "General info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances",
   "type": "stat",
   "description": "Number of AM instances managing alert notifications",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alertmanager_build_info{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Receivers",
   "type": "stat",
   "description": "Current number of receivers (notification methods email,pagerduty...)",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_receivers{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Failed Notif",
   "type": "stat",
   "description": "Total number of failed notifications (email...)",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(alertmanager_notifications_failed_total{instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "stat",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"active\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Suppressed",
   "type": "stat",
   "description": "Current number of suppressed alerts.",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"suppressed\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Silences",
   "type": "stat",
   "description": "Current number of active silences.",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_silences{state=\"active\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Instance versions and up time",
   "type": "table",
   "description": "Table containing list of Alertmanager instances showing it's version, up time, last reload time and if it was successful.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "time() - (alertmanager_build_info{instance=~\"$instance\"}*on (instance) group_left process_start_time_seconds{job=\"prometheus-alertmanager\", instance=~\"$instance\"})"
    },
    {
     "expr": "time() - alertmanager_config_last_reload_success_timestamp_seconds{instance=~\"$instance\"}"
    },
    {
     "expr": "alertmanager_config_last_reload_successful{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU Usage",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{container=\"alertmanager\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container=\"alertmanager\"}[$interval]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{container=\"alertmanager\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Memory usage (RSS) and Golang internals",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus-alertmanager\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "max_over_time(go_memstats_alloc_bytes{job=\"prometheus-alertmanager\"}[$interval])",
     "legendFormat": "Max Go"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"prometheus-alertmanager\"}",
     "legendFormat": "Allocated bytes"
    },
    {
     "expr": "min_over_time(go_memstats_alloc_bytes{job=\"prometheus-alertmanager\"}[$interval])",
     "legendFormat": "Min Go"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{container=\"alertmanager\"})",
     "legendFormat": "Req"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{container=\"alertmanager\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Alert States",
   "type": "timeseries",
   "description": "Number of alerts by state such as `active`, `suppressed` etc.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (state)(alertmanager_alerts{instance=~\"$instance\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Received Alert Status",
   "type": "timeseries",
   "description": "Number of received alerts from Prometheus by status `firing` on positive axis and `resolved` on negative axis.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(alertmanager_alerts_received_total{instance=~\"$instance\"}[$__interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Notifications Sent",
   "type": "timeseries",
   "description": "Number of sent notifications to distinct integrations such as PagerDuty, Slack and so on. On negative axis are displayed failed notifications.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(alertmanager_notifications_total{instance=~\"$instance\"}[$interval])) by (integration)",
     "legendFormat": "{{ integration}}"
    },
    {
     "expr": "sum(increase(alertmanager_notifications_failed_total{instance=~\"$instance\"}[$interval])) by (integration)",
     "legendFormat": "Failed {{ integration }}"
    }
   ]
  },
  {
   "title": "Notification Duration Integrations",
   "type": "timeseries",
   "description": "Duration of notification sends in 0.99 and 0.9 quantiles per integration.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.9,rate(alertmanager_notification_latency_seconds_bucket{instance=~\"$instance\"}[$__interval]))) by (integration)",
     "legendFormat": "0.9q {{ integration }}"
    },
    {
     "expr": "sum(histogram_quantile(0.99,rate(alertmanager_notification_latency_seconds_bucket{instance=~\"$instance\"}[$__interval]))) by (integration)",
     "legendFormat": "0.99q {{ integration }}"
    }
   ]
  }
 ]
}