apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: request-duration
  namespace: flagger-system
spec:
  provider:
    type: prometheus
    address: http://prometheus-server.monitor.svc.cluster.local
  query: |
    histogram_quantile(
      0.99,
      sum(
        rate(
          istio_request_duration_milliseconds_bucket{
            reporter="destination",
            destination_service_namespace="{{ namespace }}",
            destination_service_name=~"{{ target }}(-primary)?"
          }[5m]
        )
      ) by (le)
    )
