apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- ../base
  #- ../base/repos
  - ../base/namespaces
  - ../base/crds
  - ../base/istio-base
  - ../base/istiod
  #- ../base/metrics-server
  #- ../base/prometheus
  #- ../base/prometheus-adapter
  #- ../base/kube-state-metrics
  #- ../base/flagger
  #- ../base/grafana
  #- ../base/kiali
  #- ../base/aspire
  #- ../base/locust
# patches:
#   - path: ./patches/istio-ingress-patch.yaml
